import type { Metadata } from "next";
import Header from "@/components/layout/Header";
import SWRProvider from "@/components/providers/SWRProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <title>DOGCATSTAR</title>
      </head>
      <body className={inter.className}>
        <SWRProvider>
          <Header />
          {children}
        </SWRProvider>
      </body>
    </html>
  );
}
